apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsu.fullname" . }}-secrets
type: Opaque
stringData:
  JITSU_AUTH_SECRET: {{ .Values.secrets.JITSU_AUTH_SECRET | quote }}
  SMTP_HOST: {{ .Values.secrets.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.secrets.SMTP_PORT | quote }}
  SMTP_USER: {{ .Values.secrets.SMTP_USER | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.SMTP_PASSWORD | quote }}
